<a href="https://colab.research.google.com/github/Dearmener/learning-deep-with-limu/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

#张量

tensor_A = torch.arange(12).reshape(3,4)
tensor_B = torch.arange(12,24).reshape(3,4)

tensor_A,tensor_B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]))

In [5]:
# cat 使用cat进行拼接
cat_0 = torch.cat((tensor_A,tensor_B),dim=0) #按行拼接
cat_1 = torch.cat((tensor_A,tensor_B),dim=1) #按列拼接
cat_0,cat_1

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]),
 tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
         [ 4,  5,  6,  7, 16, 17, 18, 19],
         [ 8,  9, 10, 11, 20, 21, 22, 23]]))

In [8]:
# 广播机制
board_A = torch.arange(12).reshape(3,4)
board_B = torch.arange(12,16)
board_A+board_B

tensor([[12, 14, 16, 18],
        [16, 18, 20, 22],
        [20, 22, 24, 26]])

In [12]:
# 截取
dcut_A = torch.arange(12).reshape(3,4)
dcut_A,dcut_A[:,0:2]
dcut_A,dcut_A[0:2,:]
dcut_A,dcut_A[1:3,1:3]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 5,  6],
         [ 9, 10]]))

In [ ]:
# 数据操作


In [15]:
import os
import pandas as pd

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [17]:
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [20]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2:3]
inputs,outputs

(   NumRooms Alley
 0       NaN  Pave
 1       2.0   NaN
 2       4.0   NaN
 3       NaN   NaN,
     Price
 0  127500
 1  106000
 2  178100
 3  140000)

In [21]:
inputs = inputs.fillna(inputs.mean())
inputs

<ipython-input-21-98687b4cf42f>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  inputs = inputs.fillna(inputs.mean())


NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [22]:
inputs = pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [25]:
inputs_tensor,outputs_tensor = torch.tensor(inputs.values),torch.tensor(outputs.values)
inputs_tensor,outputs_tensor

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([[127500],
         [106000],
         [178100],
         [140000]]))

In [27]:
all = torch.cat((inputs_tensor,outputs_tensor),dim=1)
all

tensor([[3.0000e+00, 1.0000e+00, 0.0000e+00, 1.2750e+05],
        [2.0000e+00, 0.0000e+00, 1.0000e+00, 1.0600e+05],
        [4.0000e+00, 0.0000e+00, 1.0000e+00, 1.7810e+05],
        [3.0000e+00, 0.0000e+00, 1.0000e+00, 1.4000e+05]], dtype=torch.float64)