In [17]:
import torch
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [2]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190))

In [12]:
# 求平均值
A.sum()/A.numel() #使用A的总和除以A中元素的总数目
A.mean()

tensor(9.5000)

In [8]:
#指定按照某一个维度求和 降维求和
A_sum_axis0 = A.sum(axis=0) #按照行求和
A_sum_axis0.shape,A_sum_axis0

(torch.Size([4]), tensor([40, 45, 50, 55]))

In [9]:
A_sum_axis11 = A.sum(axis = 1)
A_sum_axis11

tensor([ 6, 22, 38, 54, 70])

In [12]:
#创建一个三维的张量
B_3D = torch.arange(3*4*5).reshape(3,4,5)
B_3D

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

In [11]:
# 对axis=0进行求和
B_3D_sum_axis0 = B_3D.sum(axis=0)
B_3D_sum_axis0

tensor([[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]])

In [13]:
B_3D_sum_axis1 = B_3D.sum(axis=1)
B_3D_sum_axis1

tensor([[ 30,  34,  38,  42,  46],
        [110, 114, 118, 122, 126],
        [190, 194, 198, 202, 206]])

In [14]:
# 对A的某一个维度求平均值
A_mean0 = A.mean(axis=0) #这里A是一个二维的张量，所以axis=0是按照行求平均值
A_mean0 

tensor([ 8.,  9., 10., 11.])

In [18]:
A_mean1 = A.mean(axis=1) #这里A是一个二维的张量，所以axis=1是按照列求平均值
A_mean1

tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000])

In [25]:
# 非降维求和
A.sum(axis =1 ,keepdim=True) #keepdim=True 保持维度不变

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [26]:
A.cumsum(axis=0) #按照行累加，得到一个二维的张量，每一行都是前面所有行的和，所以是一个二维的张量

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [ ]:
A.sum(axis=0,keepdim=True) #按照行求和，保持维度不变

## 点积
只能用在向量中

In [31]:
dot_a = torch.arange(5)
dot_b = torch.arange(5,10)
dot_a,dot_b

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]))

In [32]:
# 使用torch.dot()求两个向量的点积
torch.dot(dot_a,dot_b)

tensor(80)

In [35]:
#使用sum求两个向量的点积
(dot_a*dot_b).sum() 

tensor(80)

In [36]:
torch.sum(dot_a*dot_b)

tensor(80)

## 矩阵-向量集
矩阵与向量相乘

In [41]:
motrix_a = torch.arange(12).reshape(3,4)
vetory_b = torch.arange(4)

motrix_a,vetory_b,torch.mv(motrix_a,vetory_b),vetory_b.shape #使用torch.mv()求矩阵和向量的乘积

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([0, 1, 2, 3]),
 tensor([14, 38, 62]),
 torch.Size([4]))

## 矩阵与矩阵相乘


In [43]:
matrix_c = torch.arange(12).reshape(3,4)
matrix_d = torch.arange(12,24).reshape(4,3)
matrix_c,matrix_d,torch.mm(matrix_c,matrix_d)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]),
 tensor([[114, 120, 126],
         [378, 400, 422],
         [642, 680, 718]]))

## hadamard积

In [44]:
# hadamard积，矩阵每一个元素一一相乘
matrix_e = torch.arange(12).reshape(3,4)
matrix_f = torch.arange(12,24).reshape(3,4)
matrix_e,matrix_f,matrix_e*matrix_f

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]),
 tensor([[  0,  13,  28,  45],
         [ 64,  85, 108, 133],
         [160, 189, 220, 253]]))

## 范数
范数是用来表示一个向量有多大

$L_2$范数的公式：

$$\left\Vert x \right\Vert_2 = \sqrt{\sum_{i=1}^n x_i^2}$$

其中$x$是一个$n$维向量，$x_i$是向量$x$的第$i$个元素。

$L_1$范数的公式：

$$\left\Vert x \right\Vert_1 = {\sum_{i=1}^n \left| x_i \right|}$$

其中$x$是一个$n$维向量，$x_i$是向量$x$的第$i$个元素。


In [50]:
#L_1范数 求向量的绝对值之和
A_L1 = torch.arange(6,dtype=torch.float32)
A_L1,torch.abs(A_L1).sum()

(tensor([0., 1., 2., 3., 4., 5.]), tensor(15.))

In [51]:
# L_2范数 求向量的平方和再开方
A_L2 = torch.norm(A_L1)
A_L2

tensor(7.4162)

In [52]:
# 或者写为
A_l2 = torch.sqrt(torch.sum(A_L1**2))
A_l2

tensor(7.4162)

## F范数
$F$范数也叫矩阵的弗罗贝尼乌斯范数，它的公式如下：

$$\left\Vert A \right\Vert_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n \left| a_{ij} \right|^2}$$

其中$A$是一个$m \times n$的矩阵，$a_{ij}$是矩阵$A$的第$i$行第$j$列的元素。


In [53]:
F_A = torch.arange(12,dtype=torch.float32).reshape(3,4)
F_A_F = torch.norm(F_A)
F_A_F

tensor(22.4944)

In [54]:
F_A_F = torch.sqrt(torch.sum(F_A**2))
F_A_F

tensor(22.4944)

: 