In [9]:
import torch

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape

12

In [10]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
torch.zeros(2,2,3,4)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [16]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[1,2,3,1],[4,5,6,4],[7,8,9,9]]).type(torch.float32)
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[1., 2., 3., 1.],
         [4., 5., 6., 4.],
         [7., 8., 9., 9.]]))

In [17]:
# 将X与Y合并
torch.cat((X,Y),dim=0)#按行合并

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  1.],
        [ 4.,  5.,  6.,  4.],
        [ 7.,  8.,  9.,  9.]])

In [18]:
torch.cat((X,Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  1.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  4.],
        [ 8.,  9., 10., 11.,  7.,  8.,  9.,  9.]])

In [21]:
X_1 = torch.arange(36).reshape((3,3,4))
X_2 = torch.arange(36,72).reshape((3,3,4))
X_1,X_2


(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]],
 
         [[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]]]),
 tensor([[[36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]],
 
         [[48, 49, 50, 51],
          [52, 53, 54, 55],
          [56, 57, 58, 59]],
 
         [[60, 61, 62, 63],
          [64, 65, 66, 67],
          [68, 69, 70, 71]]]))

In [20]:
torch.cat((X_1,X_2),dim=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71]]])

In [22]:
torch.cat((X_1,X_2),dim=1)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23],
         [48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71]]])

In [28]:
X_1_union_X_2_column = torch.cat((X_1,X_2),dim=2)
X_1_union_X_2_column

X_1_union_X_2_column.sum()

tensor(2556)

## 广播机制


In [30]:
a = torch.arange(3).reshape(3,1)

b = torch.arange(3,5).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[3, 4]]))

In [31]:
a+b

tensor([[3, 4],
        [4, 5],
        [5, 6]])

In [41]:
a_1 = torch.arange(12).reshape(3,4)
a_2 = torch.arange(3,9).reshape(3,2)

In [43]:
a_1,a_2
a_1+a_2

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1